Change version in CMakeLists when publish workflow is run, commit new version

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -13,6 +13,8 @@ on:
       publish-version:
         description: "new version that should get published"
         required: true
+permissions:
+  contents: write
 
 jobs:
   build:
@@ -74,6 +76,21 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: true
+          fetch-depth: 0
+
+      - name: Update Version in CMakeLists
+        run: |
+          publish_version="${{ inputs.publish-version }}"
+          cmake_version=$(grep -Po '(?<=set\s*\(\s*CMAKE_PROJECT_VERSION\s*")[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
+          if ! [[ $publish_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Invalid version format for publish-version: $publish_version. It must be in the format x.y.z."
+            exit 1
+          fi
+          if [ "$(printf "%s\n%s" "$cmake_version" "$publish_version" | sort -V | head -n1)" != "$cmake_version" ] || [ "$cmake_version" == "$publish_version" ]; then
+              echo "CMake version $cmake_version is not smaller than publish-version $publish_version."
+              exit 1
+          fi
+          sed -i -E "s/(set\s*\(\s*CMAKE_PROJECT_VERSION\s*\")[0-9]+\.[0-9]+\.[0-9]+(\")/\1${publish_version}\2/" CMakeLists.txt
 
       - name: Create build directory
         run: mkdir -p build
@@ -117,4 +134,21 @@ jobs:
         with:
           name: ${{ steps.cpack.outputs.filename }}
           path: ${{ steps.cpack.outputs.filepath }}
+
+  release:
+    runs-on: ubuntu
+    needs: build
+    steps:
+      - name: Update Version in CMakeLists
+        run: |
+          sed -i -E "s/(set\s*\(\s*CMAKE_PROJECT_VERSION\s*\")[0-9]+\.[0-9]+\.[0-9]+(\")/\1${{ inputs.publish-version }}\2/" CMakeLists.txt
+      - name: Create Relase
+        shell: bash
+        if: false
+        run: |
+          git config --global user.name 'alex1701c'
+          git config --global user.email 'alex1701c@users.noreply.github.com'
+          git commit -am "New release ${{ inputs.publish-version }}"
+          git tag -a "${{ inputs.publish-version }}" -m "Release version ${{ inputs.publish-version }}"
+          git push
 
